### ISSUE TITLE
Enable Springboot log output in the Cloud console:

### ISSUE THREAD

**Issue by ludoch** [michaeltecourt/appengine-spring-boot#1]
To see the Springboot log entries in the GAE console, you need to exclude jul-to-slf4j:

`        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-tomcat</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>jul-to-slf4j</artifactId>
                </exclusion>
            </exclusions>
        </dependency>`

**Comment by michaeltecourt** [comment]
👍 thanks !
